### ISSUE TITLE
Fatal Error on RPI (armv7l) when running Katana

### ISSUE THREAD

**Issue by DeC1pher** [projectdiscovery/katana#325]
Hi Team,

I just updated GoLang to `1.20.1` and Iam getting following Stacktrace right after running:

```
runtime: g 1: unexpected return pc for runtime.doInit called from 0x0
stack: frame={sp:0x250fc80, fp:0x250fda8} stack=[0x2508000,0x2510000)
0x0250fc00:  0x0250fb98  0x008ab540  0x013394c8  0x00000000
0x0250fc10:  0x0004dc60 <runtime.runOpenDeferFrame+0x000001c0>  0x0250fb9c  0x00000100  0x00067884 <runtime.sigpanic+0x0000026c>
0x0250fc20:  0x008ab540  0x013394c8  0x0068abcc <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000fc>  0x00000001
0x0250fc30:  0x00002000  0x00000000  0x00000000  0x00000000
0x0250fc40:  0x020020f0  0x0068abcc <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000fc>  0x00060abc <runtime.doInit+0x00000054>  0x012f7080
0x0250fc50:  0x01388f58  0x00000000  0x002ceae4 <encoding/json.stateBeginValue+0x00000294>  0x0010d601 <os.hostname+0x000001e5>
0x0250fc60:  0x00010001  0xaceb4ca0  0xb6d5f088  0x00e5f950
0x0250fc70:  0x01375d40  0x00000000  0x00000000  0x00887278
0x0250fc80: <0x00000000  0x00000003  0x0225cf80  0x0001ec24 <runtime.mallocgc+0x00000744>
0x0250fc90:  0x0001ec24 <runtime.mallocgc+0x00000744>  0x000275e8 <runtime.heapBitsSetType+0x00000298>  0x00000005  0x00000003
0x0250fca0:  0x0001ec24 <runtime.mallocgc+0x00000744>  0x023add80  0x00000001  0x00000000
0x0250fcb0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fcc0:  0x00000000  0x00000000  0x00000000  0x01374140
0x0250fcd0:  0x0001e2ec <runtime.(*mcache).nextFree+0x00000044>  0xadeb5e98  0x00000010  0x00000100
0x0250fce0:  0x00000080  0x0000007f  0x0001eaa0 <runtime.mallocgc+0x000005c0>  0x0001e60c <runtime.mallocgc+0x0000012c>
0x0250fcf0:  0x0001e60c <runtime.mallocgc+0x0000012c>  0x0001f120 <runtime.newobject+0x0000002c>  0x0001ec70 <runtime.mallocgc+0x00000790>  0x0001ec70 <runtime.mallocgc+0x00000790>
0x0250fd00:  0x0001e60c <runtime.mallocgc+0x0000012c>  0x0207f420  0x00000070  0x0001ec70 <runtime.mallocgc+0x00000790>
0x0250fd10:  0x0001f120 <runtime.newobject+0x0000002c>  0x00000008  0x00000000  0x00000004
0x0250fd20:  0x008a6fc8  0xb6d5f088  0x00020070 <runtime.makeBucketArray+0x000000f0>  0x01370001
0x0250fd30:  0xadeb61d4  0xb6d5f088  0x00000010  0x01375d40
0x0250fd40:  0x023bc070  0x00000000  0x004d61d4 <github.com/projectdiscovery/gologger.init.0+0x000000c0>  0x00000008
0x0250fd50:  0x008cad10  0x0225d001  0x023bc070  0x00060b78 <runtime.doInit+0x00000110>
0x0250fd60:  0x008cad10  0x023bc070  0x012f44b4  0x023add80
0x0250fd70:  0x00060abc <runtime.doInit+0x00000054>  0x012f4498  0x00000000  0x00000000
0x0250fd80:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fd90:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fda0:  0x00000000  0x00000000 >0x00000001  0x0000000b
0x0250fdb0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fdc0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fdd0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fde0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fdf0:  0x0003db64 <runtime.(*mheap).alloc+0x00000058>  0x00028ef0 <runtime.(*mcentral).grow+0x00000060>  0x00028f30 <runtime.(*mcentral).grow+0x000000a0>  0xb6d6b1c4
0x0250fe00:  0x0003db84 <runtime.(*mheap).alloc.func1+0x00000000>  0x0137a1a0  0x00000001  0x020425fc
0x0250fe10:  0x0000000c  0x00028a68 <runtime.(*mcentral).cacheSpan+0x00000110>  0xb6d6b1c4  0x00000000
0x0250fe20:  0x00028a0c <runtime.(*mcentral).cacheSpan+0x000000b4>  0xb6d6b1c4
fatal error: unknown caller pc

runtime stack:
runtime.throw({0x983258, 0x11})
        /usr/local/go/src/runtime/panic.go:1047 +0x4c fp=0xbef14328 sp=0xbef14314 pc=0x4e714
runtime.gentraceback(0x68abcc, 0x250fc48, 0x0, 0x20020f0, 0x0, 0x0, 0x7fffffff, 0xbef1455c, 0x0, 0x0)
        /usr/local/go/src/runtime/traceback.go:270 +0x1880 fp=0xbef1452c sp=0xbef14328 pc=0x77150
runtime.addOneOpenDeferFrame.func1()
        /usr/local/go/src/runtime/panic.go:645 +0x8c fp=0xbef14568 sp=0xbef1452c pc=0x4d7c4
runtime.systemstack()
        /usr/local/go/src/runtime/asm_arm.s:317 +0x60 fp=0xbef1456c sp=0xbef14568 pc=0x8260c

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_arm.s:274 +0x4 fp=0x250faf0 sp=0x250faec pc=0x825a0
runtime.addOneOpenDeferFrame(0x20020f0, 0x0, 0x0)
        /usr/local/go/src/runtime/panic.go:644 +0x70 fp=0x250fb0c sp=0x250faf0 pc=0x4d720
panic({0x8ab540, 0x13394c8})
        /usr/local/go/src/runtime/panic.go:886 +0x258 fp=0x250fb68 sp=0x250fb0c pc=0x4e0fc
runtime.panicmem()
        /usr/local/go/src/runtime/panic.go:260 +0x4c fp=0x250fb74 sp=0x250fb68 pc=0x4ca5c
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:837 +0x26c fp=0x250fb90 sp=0x250fb74 pc=0x67884
runtime.deferCallSave(0x250fc00, 0x887278)
        /usr/local/go/src/runtime/panic.go:791 +0x84 fp=0x250fb9c sp=0x250fb94 pc=0x4de50
runtime.runOpenDeferFrame(0x2094180)
        /usr/local/go/src/runtime/panic.go:769 +0x1c0 fp=0x250fbc0 sp=0x250fb9c pc=0x4dc60
panic({0x8ab540, 0x13394c8})
        /usr/local/go/src/runtime/panic.go:884 +0x218 fp=0x250fc1c sp=0x250fbc0 pc=0x4e0bc
runtime.panicmem()
        /usr/local/go/src/runtime/panic.go:260 +0x4c fp=0x250fc28 sp=0x250fc1c pc=0x4ca5c
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:837 +0x26c fp=0x250fc44 sp=0x250fc28 pc=0x67884
github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw()
        /home/pi/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.4-0.20221222195055-f7d250fc55af/permission/permission_linux.go:40 +0xfc fp=0x250fc80 sp=0x250fc48 pc=0x68abcc
runtime: g 1: unexpected return pc for runtime.doInit called from 0x0
stack: frame={sp:0x250fc80, fp:0x250fda8} stack=[0x2508000,0x2510000)
0x0250fc00:  0x0250fb98  0x008ab540  0x013394c8  0x00000000
0x0250fc10:  0x0004dc60 <runtime.runOpenDeferFrame+0x000001c0>  0x0250fb9c  0x00000100  0x00067884 <runtime.sigpanic+0x0000026c>
0x0250fc20:  0x008ab540  0x013394c8  0x0068abcc <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000fc>  0x00000001
0x0250fc30:  0x00002000  0x00000000  0x00000000  0x00000000
0x0250fc40:  0x020020f0  0x0068abcc <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000fc>  0x00060abc <runtime.doInit+0x00000054>  0x012f7080
0x0250fc50:  0x01388f58  0x00000000  0x002ceae4 <encoding/json.stateBeginValue+0x00000294>  0x0010d601 <os.hostname+0x000001e5>
0x0250fc60:  0x00010001  0xaceb4ca0  0xb6d5f088  0x00e5f950
0x0250fc70:  0x01375d40  0x00000000  0x00000000  0x00887278
0x0250fc80: <0x00000000  0x00000003  0x0225cf80  0x0001ec24 <runtime.mallocgc+0x00000744>
0x0250fc90:  0x0001ec24 <runtime.mallocgc+0x00000744>  0x000275e8 <runtime.heapBitsSetType+0x00000298>  0x00000005  0x00000003
0x0250fca0:  0x0001ec24 <runtime.mallocgc+0x00000744>  0x023add80  0x00000001  0x00000000
0x0250fcb0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fcc0:  0x00000000  0x00000000  0x00000000  0x01374140
0x0250fcd0:  0x0001e2ec <runtime.(*mcache).nextFree+0x00000044>  0xadeb5e98  0x00000010  0x00000100
0x0250fce0:  0x00000080  0x0000007f  0x0001eaa0 <runtime.mallocgc+0x000005c0>  0x0001e60c <runtime.mallocgc+0x0000012c>
0x0250fcf0:  0x0001e60c <runtime.mallocgc+0x0000012c>  0x0001f120 <runtime.newobject+0x0000002c>  0x0001ec70 <runtime.mallocgc+0x00000790>  0x0001ec70 <runtime.mallocgc+0x00000790>
0x0250fd00:  0x0001e60c <runtime.mallocgc+0x0000012c>  0x0207f420  0x00000070  0x0001ec70 <runtime.mallocgc+0x00000790>
0x0250fd10:  0x0001f120 <runtime.newobject+0x0000002c>  0x00000008  0x00000000  0x00000004
0x0250fd20:  0x008a6fc8  0xb6d5f088  0x00020070 <runtime.makeBucketArray+0x000000f0>  0x01370001
0x0250fd30:  0xadeb61d4  0xb6d5f088  0x00000010  0x01375d40
0x0250fd40:  0x023bc070  0x00000000  0x004d61d4 <github.com/projectdiscovery/gologger.init.0+0x000000c0>  0x00000008
0x0250fd50:  0x008cad10  0x0225d001  0x023bc070  0x00060b78 <runtime.doInit+0x00000110>
0x0250fd60:  0x008cad10  0x023bc070  0x012f44b4  0x023add80
0x0250fd70:  0x00060abc <runtime.doInit+0x00000054>  0x012f4498  0x00000000  0x00000000
0x0250fd80:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fd90:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fda0:  0x00000000  0x00000000 >0x00000001  0x0000000b
0x0250fdb0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fdc0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fdd0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fde0:  0x00000000  0x00000000  0x00000000  0x00000000
0x0250fdf0:  0x0003db64 <runtime.(*mheap).alloc+0x00000058>  0x00028ef0 <runtime.(*mcentral).grow+0x00000060>  0x00028f30 <runtime.(*mcentral).grow+0x000000a0>  0xb6d6b1c4
0x0250fe00:  0x0003db84 <runtime.(*mheap).alloc.func1+0x00000000>  0x0137a1a0  0x00000001  0x020425fc
0x0250fe10:  0x0000000c  0x00028a68 <runtime.(*mcentral).cacheSpan+0x00000110>  0xb6d6b1c4  0x00000000
0x0250fe20:  0x00028a0c <runtime.(*mcentral).cacheSpan+0x000000b4>  0xb6d6b1c4
runtime.doInit(0xb)
        /usr/local/go/src/runtime/proc.go:6483 +0x54 fp=0x250fda8 sp=0x250fc80 pc=0x60abc

goroutine 2 [force gc (idle)]:
runtime.gopark(0xc543d4, 0x1374b08, 0x11, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x2042fd8 sp=0x2042fc4 pc=0x51b44
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xd4 fp=0x2042fec sp=0x2042fd8 pc=0x51964
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x2042fec sp=0x2042fec pc=0x8422c
created by runtime.init.5
        /usr/local/go/src/runtime/proc.go:293 +0x1c

goroutine 18 [GC sweep wait]:
runtime.gopark(0xc543d4, 0x13751f8, 0xc, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x203e7c8 sp=0x203e7b4 pc=0x51b44
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x2068000)
        /usr/local/go/src/runtime/mgcsweep.go:319 +0x104 fp=0x203e7e4 sp=0x203e7c8 pc=0x3a714
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x203e7ec sp=0x203e7e4 pc=0x2b1dc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x203e7ec sp=0x203e7ec pc=0x8422c
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x74

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xc543d4, 0x1375660, 0xd, 0x14, 0x2)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x203efb4 sp=0x203efa0 pc=0x51b44
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1375660)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x64 fp=0x203efc8 sp=0x203efb4 pc=0x38008
runtime.bgscavenge(0x2068000)
        /usr/local/go/src/runtime/mgcscavenge.go:633 +0x64 fp=0x203efe4 sp=0x203efc8 pc=0x3874c
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x203efec sp=0x203efe4 pc=0x2b188
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x203efec sp=0x203efec pc=0x8422c
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xbc

goroutine 3 [finalizer wait]:
runtime.gopark(0xc54310, 0x1386b4c, 0x10, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x204278c sp=0x2042778 pc=0x51b44
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0xfc fp=0x20427ec sp=0x204278c pc=0x2a0b8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x20427ec sp=0x20427ec pc=0x8422c
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x5c

goroutine 4 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x202f6c8, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x2043790 sp=0x204377c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x20437ec sp=0x2043790 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x20437ec sp=0x20437ec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20

goroutine 5 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x2096000, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x2043f90 sp=0x2043f7c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x2043fec sp=0x2043f90 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x2043fec sp=0x2043fec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20

goroutine 20 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x24ba000, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x203f790 sp=0x203f77c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x203f7ec sp=0x203f790 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x203f7ec sp=0x203f7ec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x202f6e0, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x24c2790 sp=0x24c277c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x24c27ec sp=0x24c2790 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x24c27ec sp=0x24c27ec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20
```

Thanks!

**Comment by DeC1pher** [comment]
As root:

```
SIGILL: illegal instruction
PC=0x65a22 m=0 sigcode=1
instruction bytes: 0xff 0xeb 0x64 0x0 0x9d 0xe5 0x4 0x10 0x90 0xe5 0x0 0x0 0x0 0x0 0x1c 0x10

goroutine 1 [running, locked to thread]:
runtime.dumpregs(0x4)
        /usr/local/go/src/runtime/signal_arm.go:16 +0x9e fp=0x387fca4 sp=0x387fc44 pc=0x65a22
runtime: g 1: unexpected return pc for github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw called from 0x3769d80
stack: frame={sp:0x387fca4, fp:0x387fcdc} stack=[0x3878000,0x3880000)
0x0387fc24:  0x00004b5e  0xffffffff  0xffffffff  0x00002000
0x0387fc34:  0x000001ff  0x000001ff  0x00000001  0x00000000
0x0387fc44:  0x0068abf4 <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x00000124>  0x00060abc <runtime.doInit+0x00000054>  0x012f7080  0x01388f58
0x0387fc54:  0x00000000  0x002ceae4 <encoding/json.stateBeginValue+0x00000294>  0x00107701 <os.(*File).Write+0x000002c1>  0x00010001
0x0387fc64:  0xade87fb4  0xb6d342e0  0x00e5f950  0x01375d40
0x0387fc74:  0x00000000  0x00000000  0x00887278  0x00000000
0x0387fc84:  0x00000003  0x03610f80  0x0001ec24 <runtime.mallocgc+0x00000744>  0x0001ec24 <runtime.mallocgc+0x00000744>
0x0387fc94:  0x000275e8 <runtime.heapBitsSetType+0x00000298>  0x00000555  0x0000000b  0x0001ec24 <runtime.mallocgc+0x00000744>
0x0387fca4: <0x03769d80  0x00000004  0x00000000  0x00000000
0x0387fcb4:  0x00000000  0x00000000  0x00000000  0x00000000
0x0387fcc4:  0x00000000  0x00000002  0x01374140  0x0001e2ec <runtime.(*mcache).nextFree+0x00000044>
0x0387fcd4:  0xade89208  0x00000010 >0x00000100  0x00000080
0x0387fce4:  0x0000007f  0x0001eaa0 <runtime.mallocgc+0x000005c0>  0x0001e60c <runtime.mallocgc+0x0000012c>  0x0001e60c <runtime.mallocgc+0x0000012c>
0x0387fcf4:  0x0001f120 <runtime.newobject+0x0000002c>  0x0001ec70 <runtime.mallocgc+0x00000790>  0x0001ec70 <runtime.mallocgc+0x00000790>  0x0001e60c <runtime.mallocgc+0x0000012c>
0x0387fd04:  0x034a7340  0x00000070  0x0001ec70 <runtime.mallocgc+0x00000790>  0x0001f120 <runtime.newobject+0x0000002c>
0x0387fd14:  0x00000008  0x00000000  0x00000004  0x008a6fc8
0x0387fd24:  0xb6d342e0  0x00020070 <runtime.makeBucketArray+0x000000f0>  0x01370001  0xade895a0
0x0387fd34:  0xb6d342e0  0x00000010  0x01375d40  0x03773ff0
0x0387fd44:  0x00000000  0x004d61d4 <github.com/projectdiscovery/gologger.init.0+0x000000c0>  0x00000008  0x008cad10
0x0387fd54:  0x03611001  0x03773ff0
github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw()
        /home/pi/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.4-0.20221222195055-f7d250fc55af/permission/permission_linux.go:42 +0x124 fp=0x387fcdc sp=0x387fca4 pc=0x68abf4

goroutine 2 [force gc (idle)]:
runtime.gopark(0xc543d4, 0x1374b08, 0x11, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x343afd8 sp=0x343afc4 pc=0x51b44
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xd4 fp=0x343afec sp=0x343afd8 pc=0x51964
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x343afec sp=0x343afec pc=0x8422c
created by runtime.init.5
        /usr/local/go/src/runtime/proc.go:293 +0x1c

goroutine 18 [GC sweep wait]:
runtime.gopark(0xc543d4, 0x13751f8, 0xc, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x34367c8 sp=0x34367b4 pc=0x51b44
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x3460000)
        /usr/local/go/src/runtime/mgcsweep.go:319 +0x104 fp=0x34367e4 sp=0x34367c8 pc=0x3a714
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x34367ec sp=0x34367e4 pc=0x2b1dc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x34367ec sp=0x34367ec pc=0x8422c
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x74

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xc543d4, 0x1375660, 0xd, 0x14, 0x2)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x3436fb4 sp=0x3436fa0 pc=0x51b44
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1375660)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x64 fp=0x3436fc8 sp=0x3436fb4 pc=0x38008
runtime.bgscavenge(0x3460000)
        /usr/local/go/src/runtime/mgcscavenge.go:633 +0x64 fp=0x3436fe4 sp=0x3436fc8 pc=0x3874c
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x3436fec sp=0x3436fe4 pc=0x2b188
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x3436fec sp=0x3436fec pc=0x8422c
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xbc

goroutine 20 [finalizer wait]:
runtime.gopark(0xc54310, 0x1386b4c, 0x10, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x343a78c sp=0x343a778 pc=0x51b44
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0xfc fp=0x343a7ec sp=0x343a78c pc=0x2a0b8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x343a7ec sp=0x343a7ec pc=0x8422c
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x5c

goroutine 21 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x34bf590, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x3437790 sp=0x343777c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x34377ec sp=0x3437790 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x34377ec sp=0x34377ec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20

goroutine 22 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x34bf5a8, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x3437f90 sp=0x3437f7c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x3437fec sp=0x3437f90 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x3437fec sp=0x3437fec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20

goroutine 3 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x342a090, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x343b790 sp=0x343b77c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x343b7ec sp=0x343b790 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x343b7ec sp=0x343b7ec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20

goroutine 23 [GC worker (idle)]:
runtime.gopark(0xc54320, 0x34bf5c0, 0x1a, 0x14, 0x0)
        /usr/local/go/src/runtime/proc.go:381 +0x100 fp=0x3438790 sp=0x343877c pc=0x51b44
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0x100 fp=0x34387ec sp=0x3438790 pc=0x2dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:831 +0x4 fp=0x34387ec sp=0x34387ec pc=0x8422c
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x20

trap    0x6
error   0x0
oldmask 0x0
r0      0x0
r1      0x1
r2      0x0
r3      0x387fd58
r4      0x0
r5      0x0
r6      0xfffff001
r7      0xffff0010
r8      0x2
r9      0x37fd9d0
r10     0x34020f0
fp      0x138689d
ip      0x1
sp      0x387fc44
lr      0x68abf4
pc      0x65a22
cpsr    0x40000030
fault   0x1fe
```

**Comment by DeC1pher** [comment]
I fixed it myself by replacing:

```
/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.4-0.20221222195055-f7d250fc55af/permission/permission_linux.go
```

with the code from 

```
https://github.com/projectdiscovery/utils/blob/main/permission/permission_other.go
```

**Comment by ehsandeep** [comment]
this should be fixed with latets utils update.

**Comment by DeC1pher** [comment]
Hi @ehsandeep 

unfortenetly not I had to do the same again with v19
Replace the `permission_linux.go` with the `permission_other.go` file in `utils@v0.0.19`.

**Comment by Mzack9999** [comment]
@DeC1pher, would it be possible to provide the output of the `go env` command? I tried to exclude the faulty architecture, but it seems like it's not `armv7l`:

```go
//go:build darwin || freebsd || netbsd || openbsd || solaris || android || ios || (linux && armv7l)

package permissionutil
```

Thanks for your help!

**Comment by DeC1pher** [comment]
Sure:

```
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2606013599=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by dogancanbakir** [comment]
mentioning @Mzack9999 for review

**Comment by dogancanbakir** [comment]
I'm closing this issue due to inactivity. If you believe this was a mistake, please feel free to reopen it.
