### ISSUE TITLE
katana v1.0.5 segfault while crawling 400K hosts

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/katana#812]
### katana version:
1.0.5

### Current Behavior:
Crawls around 1100 URLs before crashing.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe36e0c]

goroutine 38710 [running]:
github.com/projectdiscovery/utils/url.(*URL).String(0x0)
	/home/runner/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.72/url/url.go:98 +0x2c
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).navigateRequest.func1(0xc005b6a8c0)
	/home/runner/work/katana/katana/pkg/engine/hybrid/crawl.go:68 +0x230
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Hijack).Start.func2(0x0?)
	/home/runner/work/katana/katana/pkg/engine/hybrid/hijack.go:52 +0x28
reflect.Value.call({0x13905e0?, 0xc0024ac978?, 0x100c001654e40?}, {0x1572396, 0x4}, {0xc0108d3f58, 0x1, 0xc005b6a8c0?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0x13905e0?, 0xc0024ac978?, 0xc005b6a8c0?}, {0xc0108d3f58?, 0xc012755e00?, 0xc00cd546b8?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/reflect/value.go:380 +0xb9
github.com/go-rod/rod.(*Browser).eachEvent.func1()
	/home/runner/go/pkg/mod/github.com/go-rod/rod@v0.114.1/browser.go:401 +0x3d9
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Hijack).Start.func3()
	/home/runner/work/katana/katana/pkg/engine/hybrid/hijack.go:57 +0x22
created by github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).navigateRequest in goroutine 38195
	/home/runner/work/katana/katana/pkg/engine/hybrid/crawl.go:49 +0x51b
```

### Expected Behavior:
No crash.

### Steps To Reproduce:
`katana -r resolvers.txt -d 5 -proxy http://localhost:3128 -u urls.txt -jc -aff -kf all -jsl -hl --no-sandbox -o katana.txt -ef png,gif,jpg,css,webp,jpeg`

### Anything else:
hi!

**Comment by dogancanbakir** [comment]
This is fixed https://github.com/projectdiscovery/katana/issues/767. The issue will be resolved in the upcoming release.
